#!/usr/bin/env bash
DCMD_BASE="${DCMD_BASE:-dcmd-alpine:latest}"
DCMD_IMAGE="${DCMD_IMAGE:-example-alpine:latest}"
echo "Building image: ${DCMD_IMAGE}"
docker build \
    --build-arg DCMD_BASE_ARG="${DCMD_BASE}" \
    --build-arg DCMD_IMAGE_ARG="${DCMD_IMAGE}" \
    -t "${DCMD_IMAGE}" .

