#!/usr/bin/env bash
if [[ -z "$1" ]]; then
    echo "Usage: ./setup <foundation>"
    echo ""
    echo "Example usage:"
    echo "  ./setup bionic"
    exit 1
fi

FOUNDATION=$1
DCMD_IMAGE="totalorder/dcmd-example-${FOUNDATION}:latest"
docker push "${DCMD_IMAGE}"