#!/usr/bin/env bash
DCMD_BASE="${DCMD_BASE:-alpine}"
DCMD_IMAGE="example-${DCMD_BASE}:latest"
./build && bash -c "$(docker run -i "${DCMD_IMAGE}" meta install-instructions)"
echo "Created executable ./exa"
