#!/usr/bin/env bash
if [[ -z "$1" ]]; then
    echo "Usage: ./build-foundation <foundation>"
    echo ""
    echo "Example usage:"
    echo "  ./build-foundation bionic"
    exit 1
fi

FOUNDATION=$1
(cd "foundations/${FOUNDATION}" && ./build) && DCMD_FOUNDATION="totalorder/dcmd-foundation-${FOUNDATION}" DCMD_BASE="totalorder/dcmd-${FOUNDATION}" ./build
