#!/usr/bin/env bash
if [[ -z "$1" ]]; then
    echo "Usage: ./setup <foundation>"
    echo ""
    echo "Example usage:"
    echo "  ./setup bionic"
    exit 1
fi

set -e
FOUNDATION=$1
shift
DCMD_BASE="totalorder/dcmd-${FOUNDATION}"

if [[ $1 != "--no-foundation" ]]; then
    ./build-foundation "${FOUNDATION}"
else
    shift
    DCMD_FOUNDATION="totalorder/dcmd-foundation-${FOUNDATION}" DCMD_BASE="totalorder/dcmd-${FOUNDATION}" ./build
fi

bash -c "$(docker run -i "${DCMD_BASE}" meta install-instructions "$@")"
if [[ $? != 0 ]]; then
    echo "Failed to create executable ./dcmd with install instructions: $(docker run -i "${DCMD_BASE}" meta install-instructions)"
fi
