#!/usr/bin/env bash

CMD_PATH="."
CMD_NAME="$(cat /.dcmd-name)"
while (($#)); do
    NEXT_CMD_PATH="${CMD_PATH}/$1"
    if [[ -d "${NEXT_CMD_PATH}" ]]; then
        CMD_PATH="${NEXT_CMD_PATH}"
        CMD_NAME="${CMD_NAME} $1"
        shift
    elif [[ -f "${NEXT_CMD_PATH}" ]]; then
        CMD_PATH="${NEXT_CMD_PATH}"
        CMD_NAME="${CMD_NAME} $1"
        shift
        break
    else
        break
    fi
done

if [[ -d "${CMD_PATH}" ]]; then
    /dcmd/meta/help "${CMD_PATH}" "${CMD_NAME}"
    exit 1
fi

${CMD_PATH} "$@"
