#!/usr/bin/env bash
cat << EOF | cat
#!/usr/bin/env bash
DCMD_NAME="${DCMD_NAME}"
DCMD_IMAGE="${DCMD_IMAGE}"
EOF

cat /.executable | sed -e '/DCMD_EXECUTABLE_EXTRAS_PLACEHOLDER/ {' -e 'r /.executable-extras' -e 'd' -e '}'

