#!/usr/bin/env bash
source /shared/bash-setup
source /shared/utils

__meta__help () {
    [[ ! -z "$1" ]] && echo "$1" >&2
    cat << EOF >&2
Usage: help <command-path> <command-name> [--no-header]
EOF
    exit 1
}

__validate_num_args 2 "$#" "__meta__help"

CMD_PATH=$1
CMD_NAME=$2
HELP_COMMAND="${CMD_PATH}/.help"

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--no-header)
        NO_HEADER="y"
        shift
        ;;
        *)
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done
set -- "${POSITIONAL[@]}"

if [[ -z "${NO_HEADER:-}" ]]; then
    if [[ -f "${HELP_COMMAND}" ]]; then
        echo "${CMD_NAME} - $(${HELP_COMMAND} "${CMD_PATH}" "${CMD_NAME}")"
        exit 0
    fi

    echo "${CMD_NAME}"
fi

GLOBAL_OPT_PATH="${CMD_PATH}/.options"
if [[ -f "${GLOBAL_OPT_PATH}" ]]; then
    echo ""
    echo "global options:"

    IFS=$'\n'
    for OPT_LINE in $(${GLOBAL_OPT_PATH}); do
        IFS=' '
        declare -a OPT_COLUMNS
        OPT_COLUMNS=(${OPT_LINE})
        if [[ ${#OPT_COLUMNS[@]} -lt 4 ]]; then
            echo ".options must output lines with at least 4 items separated by space"
            echo "Example: DRY_RUN -d --dry-run Do a dry run"
            echo "Invalid line: ${OPT_LINE}"
            exit 1
        fi

        VAR_NAME="${OPT_COLUMNS[0]}"
        OPT="${OPT_COLUMNS[1]}"
        LONGOPT="${OPT_COLUMNS[2]}"
        USAGE="${OPT_COLUMNS[@]:3}"
        LONGOPT_NOPARAM="$(echo "${LONGOPT}" | sed 's/:$//g')"

        echo "    ${OPT}, ${LONGOPT_NOPARAM} ${USAGE}"
    done
    unset IFS
fi

echo ""
echo "commands:"
LONGEST_SUBCMD_NAME="$(ls "${CMD_PATH}" | awk '{ print length($1) }' | sort -nr | head -1)"
for SUBCMD_PATH in $(ls "${CMD_PATH}"); do
    # Skip all non-executable files
    if [[ -f "${CMD_PATH}/${SUBCMD_PATH}" && ! -x "${CMD_PATH}/${SUBCMD_PATH}" ]]; then
        continue
    fi

    HELP_COMMAND="${CMD_PATH}/.help.${SUBCMD_PATH}"
    SUBFOLDER_HELP_COMMAND="${CMD_PATH}/${SUBCMD_PATH}/.help"
    PADDED_SUBCMD_PATH="$(printf "%-$((${LONGEST_SUBCMD_NAME} + 2))s" ${SUBCMD_PATH})"
    if [[ -f "${HELP_COMMAND}" ]]; then
        echo "    ${PADDED_SUBCMD_PATH} $(${HELP_COMMAND} "${CMD_PATH}/${SUBCMD_PATH}" "${SUBCMD_PATH}" --description-only)"
    elif [[ -f "${SUBFOLDER_HELP_COMMAND}" ]]; then
        echo "    ${PADDED_SUBCMD_PATH} $(${SUBFOLDER_HELP_COMMAND} "${CMD_PATH}/${SUBCMD_PATH}" "${SUBCMD_PATH}" --description-only)"
    else
        echo "    ${PADDED_SUBCMD_PATH}"
    fi
done
