#!/usr/bin/env bash
cat << EOF | cat
mkdir -p "\$HOME/${DCMD_NAME}" && \
  docker run -i --rm ${DCMD_IMAGE} meta create-executable > "\$HOME/${DCMD_NAME}/${DCMD_NAME}" && \
  chmod +x "\$HOME/${DCMD_NAME}/${DCMD_NAME}" && \
  echo "Installed executable to \$HOME/${DCMD_NAME}/${DCMD_NAME}" && \
  if [ "$1" == "--non-interactive" ]; then exit 0; fi && \
  printf "Do you want \"${DCMD_NAME}\" added to your path? [Y/n] " && \
  read -r response && [[ ! "\${response}" =~ ^([nN][oO]|[nN])+$ ]] && \
  (sudo ln -sf "\$HOME/${DCMD_NAME}/${DCMD_NAME}" /usr/local/bin/${DCMD_NAME} && \
    echo -e "Created symlink from /usr/local/bin/${DCMD_NAME} to \$HOME/${DCMD_NAME}/${DCMD_NAME}.\nRun \"${DCMD_NAME}\" to start" || \
    echo "ERROR: Failed to create symlink /usr/local/bin/${DCMD_NAME}") || \
  echo "Run \"~/${DCMD_NAME}/${DCMD_NAME}\" to start"
EOF
