#!/usr/bin/env bash
if [[ ! -S "/var/run/docker.sock" ]]; then
    echo "error: Docker not available at /var/run/docker.sock"
    echo "Run \"docker pull ${DCMD_IMAGE}\" to update"
    exit 0
fi

docker pull ${DCMD_IMAGE}
if [[ $? == 0 ]]; then
    echo "Update done"
else
    echo "error: Update failed"
fi
